### ISSUE TITLE
acces par smartphone

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/analytics#18]
lorsque l on se connecte avec un smartphone sur https://talao.co/analytics 
le QR code doit etre remplacé par un bouton "Open your wallet" qui envoie le lien 

https://app.altme.io/app/download?uri=<url du QR code>

cela va ouvrir l app sur le smartphone

**Comment by achille1017** [comment]
manque un desgin pour le nouveau bouton
