### ISSUE TITLE
securité des virements

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/analytics#9]
[@Achille Dorier](https://talao.slack.com/team/U03B55J9RJM)
pour les virements, il faut un adresse gérée par le code  avec une clé qui n est pas dans le code et pas sur github. La balance de cette adresse doit être inférieure a 10 xtz apres chaque transaction ou groupe de transactions. Cf
[@Nicolas](https://talao.slack.com/team/U7NNHCWK0)
pour envoyer des xtz sur cette adresse en fonction des besoins. C est uen adresse qui est exposée il faut donc y avoir le minimum de xtz.Les virements doivent se faire sur les comptes de l affiliate qui est dans le voucher et sur le compte du gamer qui est dans le voucher.Il faut verifier que la com du gamer + com de l affiliate ne dépasse pas 20% de la transaction.Le solde (la commission de Talao ) doit être versée sur : tz1Q7zwo7fmRNyCL7jdz6hcPSsYukkWY66Q3 qui sera normalement sur le voucher mais peut être pas opérationnelle aujourd’hui...... donc il faut verifier l adresse de destination.il faut verifier que les vouchers sont signés par  did:tz:tz1RuLH4TvKNpLy3AqQMui6Hys6c1Dvik8J5 ou par did:ethr:0x9e98af48200c62f51ac9ebdcc41fe718d1be04fb et que la signature avec didkit.credential_verify ne sort pas d'erreur. (modifié)

**Comment by nicolasmullertalao** [comment]
@ThierryThevenet
On propose de mettre une alerte (notif mail) dès que le solde du compte passe en dessous 50 XTZ, et d'avoir environ 100 XTZ sur le compte en permanence
Pour la verif des 20%, il faudrait la mettre au niveau du SQR code generator mais peut être pas utile au démarrage
